/run/numberOfThreads 8
/run/initialize
/run/printProgress 1000000
/analysis/setFileName _co60
# first energy
/gps/particle gamma
/gps/pos/centre 0 0 2.54 cm
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 1.17 MeV
#
/gps/source/add 1
/gps/particle gamma
/gps/pos/centre 0 0 2.54 cm
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 1.33 MeV
#
/gps/source/multiplevertex false
/run/beamOn 1000000
